name: obs_command
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies:
  args: ^2.1.1
  colorize: ^3.0.0
  obs_websocket: ^2.2.3
  yaml: ^3.1.0

